version: '3'
services:
  go-project:
    build:
      context: ./go-project
      dockerfile: Dockerfile
    ports:
      - 9000:9000
    depends_on:
      - mongodb
    networks:
      - mynetwork

  node-project:
    build:
      context: ./node-project
      dockerfile: Dockerfile
    ports:
      - 9001:9001
    depends_on:
      - mongodb
      - redis
    networks:
      - mynetwork

  mongodb:
    container_name: mongodb
    image: mongo:latest
    volumes: 
      - mongo-data:/data/db2
    ports:
      - 27017:27017
    networks:
      - mynetwork

  redis:
    container_name: redis
    image: redis
    volumes:
      - redis_data:/bitnami/redis/data2
    ports:
      - 6379:6379
    networks:
      - mynetwork

volumes: 
    mongo-data:
    redis_data:
        driver: local

networks:
  mynetwork:
    driver: bridge
